// Regression: a compound literal of POINTER type used as a constant
// initializer was rejected as "not a compile-time constant", because
// ncc materializes file-scope compound literals as anonymous globals
// (good) but eval2's ND_VAR case errored on those globals when their
// type was TY_PTR (only TY_ARRAY / TY_FUNC were folded).
//
// The pattern is generated by Linux's STM32_GATE macro family in
// drivers/clk/clk-stm32mp1.c:
//
//     .cfg = (struct stm32_gate_cfg *) {_gate}
//
// where _gate expands to `&(struct stm32_gate_cfg){...}` — a pointer
// to another (inner) compound literal. The outer compound literal is
// a pointer-typed compound literal whose value is just that inner
// pointer; ncc should propagate the inner relocation to the outer
// initializer.
//
// Fix: in eval2 ND_VAR, when the var is an anonymous file-scope
// compound literal of TY_PTR with init_data set, fold to its single
// relocation (or to the integer value stored in init_data if there
// is no relocation).
//
// Found via: scripts/linux_scan/scan.sh on drivers/clk.
// Fixed: 2026-04-30. drivers/clk goes from 72/73 to 73/73.

struct cfg {
    int a;
    int b;
};

struct gate {
    int id;
    const char *name;
    struct cfg *p;
};

/* The pattern: pointer-typed compound literal whose initializer is
   the address of an inner compound literal. */
static const struct gate g[] = {
    {
        .id = 1,
        .name = "x",
        .p = (struct cfg *) { &(struct cfg){ .a = 1, .b = 2 } },
    },
};

/* Also exercise a pointer-typed compound literal of NULL — no relocation. */
static struct cfg *q = (struct cfg *) { 0 };

int main(void) { return 0; }
